const addUserValues = ({
  nombres = null,
  ape_paterno = null,
  ape_materno = null,
  fec_nacimiento = null,
  departamento = null,
  provincia = null,
  distrito = null,
  cod_tipo_doc = null,
  num_documento = null,
  email = null,
  direccion = null,
  telefono1 = null,
  telefono2 = null,
  username = null,
}) => ([
  cod_tipo_doc,
  num_documento,
  nombres,
  ape_paterno,
  ape_materno,
  fec_nacimiento,
  departamento,
  provincia,
  distrito,
  email,
  direccion,
  telefono1,
  telefono2,
  username,
]);

const updateUserValues = ({
  nombres = null,
  ape_paterno = null,
  ape_materno = null,
  fec_nacimiento,
  departamento = null,
  provincia = null,
  distrito = null,
  email = null,
  direccion = null,
  telefono1 = null,
  telefono2 = null,
  username = null,
  cod_usuario
}) => ([
  nombres,
  ape_paterno,
  ape_materno,
  fec_nacimiento,
  departamento,
  provincia,
  distrito,
  email,
  direccion,
  telefono1,
  telefono2,
  username,
  cod_usuario
]);

module.exports = {
  addUserValues,
  updateUserValues,
}
